#!/bin/bash
# Pulls SSM parameters to local .env.local
# Usage: ./sync-env.sh <env>

ENV=$1
if [ -z "$ENV" ]; then
  echo "Usage: $0 <env>"
  exit 1
fi

echo "Syncing $ENV secrets..."
# aws ssm get-parameters-by-path ...
# For now, just a placeholder
echo "# Generated by sync-env.sh" > .env.local
echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/velox" >> .env.local
